image: g4s8/rultor:alpine3.10
architect:
  - rocket-3
assets:
  settings.xml: "rocket-3/dbgit-test#settings.xml"
  pubring.kbx: "rocket-3/dbgit-test#pubring.kbx"
  private.asc: "rocket-3/dbgit-test#private.asc"
  public.asc: "rocket-3/dbgit-test#public.asc"
merge:
  script: |-
    pdd -f /dev/stdout
    java -version --batch-mode
    mvn -version --batch-mode -Dstyle.color=never
    mvn clean install -Pqulice -ntp --batch-mode -Dstyle.color=never
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}" -ntp -Dstyle.color=never
    export GNUPGHOME="/home/r"
    gpg --list-keys
    gpg --import ../private.asc --pinentry-mode=loopback
    gpg --import ../public.asc --pinentry-mode=loopback
    git commit -am "${tag}"
    mvn clean install -Pqulice -ntp --batch-mode -Dstyle.color=never
    mvn clean deploy -Psonatype -ntp --settings ../settings.xml -Pkeys --batch-mode -Dstyle.color=never
#
