image: g4s8/rultor:alpine3.10
architect:
  - rocket-3
assets:
  settings.xml: "rocket-3/dbgit-test#settings.xml"
  pubring.gpg: "rocket-3/dbgit-test#pubring.kbx"
merge:
  script: |-
    pdd -f /dev/stdout
    java -version --batch-mode
    mvn -version --batch-mode
    mvn clean install -Pqulice -ntp --batch-mode
release:
  script: |
    gpg --allow-secret-key-import --no-tty --batch --import /home/r/pubring.kbx
    mvn versions:set "-DnewVersion=${tag}" -ntp
    git commit -am "${tag}"
    mvn clean deploy -Psonatype -ntp --settings ../settings.xml --batch-mode
