image: g4s8/rultor:alpine3.10
architect:
  - rocket-3
assets:
  settings.xml: "rocket-3/dbgit-test#settings.xml"
  pubring.gpg: "rocket-3/dbgit-test#pubring.kbx"
merge:
  script: |-
    pdd -f /dev/stdout
    java -version --batch-mode
    mvn -version --batch-mode
    mvn clean install -Pqulice --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
release:
  script: |
    gpg --allow-secret-key-import --no-tty --batch --import /home/r/pubring.kbx
    mvn versions:set "-DnewVersion=${tag}" -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    git commit -am "${tag}"
    mvn clean deploy -Psonatype --settings ../settings.xml --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
