architect:
  - rocket-3
assets:
  settings.xml: "rocket-3/dbgit-test#settings.xml"
  pubring.gpg: "rocket-3/dbgit-test#pubring.gpg"
  secring.gpg: "rocket-3/dbgit-test#secring.gpg"
  otrust.lst: "rocket-3/dbgit-test#otrust.lst"
merge:
  script: |-
    pdd -f /dev/stdout
    java -version --batch-mode
    mvn -version --batch-mode -Dstyle.color=never
    mvn clean install -Pqulice -ntp --batch-mode -Dstyle.color=never
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}" -ntp -Dstyle.color=never
    export GNUPGHOME="/home/r"
    git commit -am "${tag}"
    mvn clean install -Pqulice -ntp --batch-mode -Dstyle.color=never
    mvn clean deploy -Psonatype -ntp --settings ../settings.xml -Pkeys --batch-mode -Dstyle.color=never
#
