name: build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    name: Like Rultor
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install pdd
        run: gem install pdd
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check Puzzles
        run: pdd --file=/dev/stdout
      - name: Check Qulice
        run: mvn clean install -Pqulice -DskipTests=true --errors --batch-mode -ntp
      - name: Check Tests
        run: mvn test --batch-mode --batch-mode -ntp
